### ISSUE TITLE
Allow for other ports than only 9000

### ISSUE THREAD

**Issue by mariussoutier** [jamesward/play-framework-chrome-tools#10]
When running multiple Play apps it's common to assign them different ports using `-Dhttp.port`. The Chrome plugin only checks port 9000 but instead should "somehow" pick up the configured port(s).

**Comment by jamesward** [comment]
I suppose we could just make it so the script matcher happens on all localhost ports by removing the port `9000` from:
https://github.com/jamesward/play-framework-chrome-tools/blob/master/src/manifest.json#L16

WDYT?

**Comment by mariussoutier** [comment]
I will try it out and report back.

**Comment by mariussoutier** [comment]
Alright, I created two pull requests. The sbt plugin will now communicate the port that is set via `-Dhttp.port` , while the Chrome plugin is enabled on all localhost windows but will only refresh the window with the matching port from the `reload:$port` message.

**Comment by jamesward** [comment]
So, Google's glob didn't work with ports.  I removed the port but now I'm not sure if this will work at all.  Here is the relevant commit: https://github.com/jamesward/play-framework-chrome-tools/commit/e682ea7d821ac946e557f917f3b9534f469dec30

The `0.0.9` release will be in the Chrome store shortly.  If this doesn't work we will have to go a different route.

**Comment by mariussoutier** [comment]
Ah, good to know. But stupid, in development mode it didn't complain.
