### ISSUE TITLE
Reloading doesn't work with /#/ routes

### ISSUE THREAD

**Issue by mariussoutier** [jamesward/play-framework-chrome-tools#11]
When using Angular's routing, reloads are no longer triggered. I'm assuming it is because of how URLs are constructed, e.g. `http://localhost:9000/#/users/1`.

**Comment by jamesward** [comment]
This is due to how the reload is done: https://github.com/jamesward/play-framework-chrome-tools/blob/master/src/play-framework-chrome-tools.js#L18

There must be a better way that works with hash URLs.

**Comment by mariussoutier** [comment]
What about `window.location.reload()`?

**Comment by jamesward** [comment]
Quick PR for this too?

**Comment by mariussoutier** [comment]
Done

**Comment by jamesward** [comment]
Thanks!
