### ISSUE TITLE
Document the configuration URL

### ISSUE THREAD

**Issue by mslinn** [jamesward/play-framework-chrome-tools#5]
chrome-extension://dchhggpgbommpcjpogaploblnpldbmen/options.htm

**Comment by jamesward** [comment]
That must be user specific because that URL doesn't work for me. :(

**Comment by mslinn** [comment]
that weird because that is the URL you gave me. The URL is derived from the chrome extension guid.

**Comment by jamesward** [comment]
Ah. Found the problem.  Your URL is missing an 'l' at the end.  So it is:

```
chrome-extension://dchhggpgbommpcjpogaploblnpldbmen/options.html
```

**Comment by jamesward** [comment]
I'll add that to the docs.
