### ISSUE TITLE
Update for Play 2.3

### ISSUE THREAD

**Issue by mariussoutier** [jamesward/play-framework-chrome-tools#9]
Error line clicking doesn't work with Play 2.3 because the error message has changed like this:

```
In /path/to/file.suffix:6
```

**Comment by mariussoutier** [comment]
This pattern should do the trick:

``` javascript
var pattern = /In ([^ ]+):([^.]+)/
```

File would be `match[1]`, line `match[2]`.

**Comment by jamesward** [comment]
Want to send a PR for that?

**Comment by mariussoutier** [comment]
Sure, will do.

**Comment by mariussoutier** [comment]
There you go.

**Comment by jamesward** [comment]
Thanks!
